# Printing and obtaining additional results for quantile regression and regression:

In [3]:
import os
import pandas as pd

original_path = os.getcwd()

def custom_table_generator(result):
    metrics = list(result.columns)[1:]

    print(f"\\begin{{tabular}}{{l{'c' * len(metrics)}}}\\toprule")
    print("Dataset & " + " & ".join(metrics) + "\\\\\\midrule")
    for _, row in result.iterrows():
        values = [row["Dataset"]]
        for metric in result.columns[1:]:
            value = row[metric]
            if pd.isna(value):
                values.append("-")
            else:
                values.append(f"{value}")
        print(" & ".join(values) + "\\\\")
    print("\\bottomrule\\end{tabular}")

Getting the results:

In [4]:
folder_path = os.path.dirname(original_path) + "/Experiments_code/results"

## Quantile regression results:

Reading pickle files and transforming to table:
* Interval length ratio between outlier and inliers:

In [6]:
output_ratio = pd.read_pickle(folder_path + "/result_ratio_outlier.pkl")
output_ratio

,Dataset,ECP-MDN,ECP-BART,ECP-GP,CQR,CQR-r,UACQR-P,UACQR-S
0,airfoil,1.048 (0.04),1.028 (0.034),1.01 (0.018),1.005 (0.013),1.004 (0.012),1.002 (0.01),1.005 (0.016)
1,bike,0.989 (0.007),0.991 (0.007),1.01 (0.007),0.985 (0.007),0.985 (0.007),0.99 (0.005),0.981 (0.01)
2,concrete,1.043 (0.029),0.983 (0.033),0.995 (0.016),0.998 (0.012),0.998 (0.012),0.998 (0.008),0.998 (0.012)
3,cycle,0.949 (0.014),0.953 (0.014),0.966 (0.014),0.997 (0.005),0.997 (0.005),1.0 (0.004),0.998 (0.007)
4,electric,1.012 (0.008),1.01 (0.004),1.01 (0.004),1.008 (0.004),1.007 (0.003),1.006 (0.003),1.01 (0.005)
5,homes,1.173 (0.027),1.116 (0.019),1.101 (0.016),1.088 (0.015),1.081 (0.014),1.039 (0.006),1.094 (0.014)
6,meps19,1.044 (0.028),1.052 (0.029),1.042 (0.025),1.04 (0.025),1.04 (0.025),1.021 (0.015),1.045 (0.026)
7,protein,1.006 (0.002),1.001 (0.002),1.001 (0.003),1.002 (0.001),1.002 (0.001),1.001 (0.001),1.002 (0.001)
8,star,0.999 (0.007),0.994 (0.006),0.994 (0.003),0.994 (0.003),0.993 (0.003),0.997 (0.003),0.997 (0.003)
9,superconductivity,1.029 (0.008),1.021 (0.007),0.987 (0.006),1.041 (0.007),1.041 (0.007),1.023 (0.004),1.049 (0.008)
10,WEC,1.02 (0.01),1.012 (0.006),1.003 (0.008),1.016 (0.003),1.016 (0.003),1.011 (0.002),1.021 (0.004)
11,winered,1.072 (0.022),1.008 (0.012),1.007 (0.008),0.993 (0.008),0.992 (0.008),0.996 (0.005),0.992 (0.009)
12,winewhite,1.053 (0.014),1.031 (0.007),1.024 (0.006),1.018 (0.007),1.018 (0.007),1.018 (0.006),1.034 (0.01)

In [7]:
custom_table_generator(output_ratio)

\begin{tabular}{lccccccc}\toprule
Dataset & ECP-MDN & ECP-BART & ECP-GP & CQR & CQR-r & UACQR-P & UACQR-S\\\midrule
airfoil & 1.048 (0.04) & 1.028 (0.034) & 1.01 (0.018) & 1.005 (0.013) & 1.004 (0.012) & 1.002 (0.01) & 1.005 (0.016)\\
bike & 0.989 (0.007) & 0.991 (0.007) & 1.01 (0.007) & 0.985 (0.007) & 0.985 (0.007) & 0.99 (0.005) & 0.981 (0.01)\\
concrete & 1.043 (0.029) & 0.983 (0.033) & 0.995 (0.016) & 0.998 (0.012) & 0.998 (0.012) & 0.998 (0.008) & 0.998 (0.012)\\
cycle & 0.949 (0.014) & 0.953 (0.014) & 0.966 (0.014) & 0.997 (0.005) & 0.997 (0.005) & 1.0 (0.004) & 0.998 (0.007)\\
electric & 1.012 (0.008) & 1.01 (0.004) & 1.01 (0.004) & 1.008 (0.004) & 1.007 (0.003) & 1.006 (0.003) & 1.01 (0.005)\\
homes & 1.173 (0.027) & 1.116 (0.019) & 1.101 (0.016) & 1.088 (0.015) & 1.081 (0.014) & 1.039 (0.006) & 1.094 (0.014)\\
meps19 & 1.044 (0.028) & 1.052 (0.029) & 1.042 (0.025) & 1.04 (0.025) & 1.04 (0.025) & 1.021 (0.015) & 1.045 (0.026)\\
protein & 1.006 (0.002) & 1.001 (0.002) & 1.001 (0.003) & 1.002 (0.001) & 1.002 (0.001) & 1.001 (0.001) & 1.002 (0.001)\\
star & 0.999 (0.007) & 0.994 (0.006) & 0.994 (0.003) & 0.994 (0.003) & 0.993 (0.003) & 0.997 (0.003) & 0.997 (0.003)\\
superconductivity & 1.029 (0.008) & 1.021 (0.007) & 0.987 (0.006) & 1.041 (0.007) & 1.041 (0.007) & 1.023 (0.004) & 1.049 (0.008)\\
WEC & 1.02 (0.01) & 1.012 (0.006) & 1.003 (0.008) & 1.016 (0.003) & 1.016 (0.003) & 1.011 (0.002) & 1.021 (0.004)\\
winered & 1.072 (0.022) & 1.008 (0.012) & 1.007 (0.008) & 0.993 (0.008) & 0.992 (0.008) & 0.996 (0.005) & 0.992 (0.009)\\
winewhite & 1.053 (0.014) & 1.031 (0.007) & 1.024 (0.006) & 1.018 (0.007) & 1.018 (0.007) & 1.018 (0.006) & 1.034 (0.01)\\
\bottomrule\end{tabular}

* AISL per outlier:

In [8]:
output_aisl = pd.read_pickle(folder_path + "/result_aisl_outlier.pkl")
output_aisl

,Dataset,ECP-MDN,ECP-BART,ECP-GP,CQR,CQR-r,UACQR-P,UACQR-S
0,airfoil,20.177 (1.585),20.445 (1.585),21.348 (1.714),22.256 (1.708),22.283 (1.711),25.665 (2.179),22.097 (1.72)
1,bike,428.977 (11.735),440.36 (10.292),463.777 (11.56),443.523 (8.565),443.526 (8.613),507.775 (13.893),419.822 (10.689)
2,concrete,46.925 (3.091),47.929 (3.895),47.62 (3.517),49.55 (3.507),49.51 (3.492),53.478 (3.195),49.516 (3.629)
3,cycle,32.565 (0.658),33.112 (0.645),33.87 (0.62),39.133 (0.622),39.347 (0.639),43.835 (0.949),35.287 (0.711)
4,electric,0.084 (0.002),0.101 (0.001),0.099 (0.002),0.105 (0.002),0.105 (0.002),0.115 (0.002),0.1 (0.002)
5,homes,940824.14 (54169.436),1063287.542 (83041.223),1102103.112 (84129.477),1149649.524 (92088.974),1169346.82 (94930.369),1762462.154 (167630.458),1316917.411 (125290.599)
6,meps19,73.538 (9.282),73.914 (8.904),74.708 (9.329),73.988 (9.315),73.987 (9.315),84.099 (10.59),72.798 (8.977)
7,protein,17.562 (0.101),17.8 (0.104),18.156 (0.109),17.804 (0.09),17.804 (0.09),18.276 (0.085),17.795 (0.091)
8,star,1039.011 (38.939),1058.143 (43.397),1044.706 (40.742),1043.497 (41.667),1043.94 (41.71),1069.002 (38.253),1064.049 (41.105)
9,superconductivity,74.955 (1.132),78.307 (1.142),82.005 (1.185),78.262 (1.097),78.263 (1.098),85.342 (1.062),76.787 (1.226)
10,WEC,258650.41 (5075.131),307021.812 (5053.901),283550.702 (5296.65),319576.121 (4757.143),320076.174 (4777.112),347431.5 (5157.103),310371.018 (4875.144)
11,winered,3.312 (0.288),3.361 (0.332),3.332 (0.328),3.369 (0.379),3.367 (0.379),3.258 (0.351),3.333 (0.343)
12,winewhite,3.969 (0.252),4.184 (0.269),4.24 (0.275),4.308 (0.292),4.306 (0.292),4.308 (0.253),4.079 (0.27)

In [9]:
custom_table_generator(output_aisl)

\begin{tabular}{lccccccc}\toprule
Dataset & ECP-MDN & ECP-BART & ECP-GP & CQR & CQR-r & UACQR-P & UACQR-S\\\midrule
airfoil & 20.177 (1.585) & 20.445 (1.585) & 21.348 (1.714) & 22.256 (1.708) & 22.283 (1.711) & 25.665 (2.179) & 22.097 (1.72)\\
bike & 428.977 (11.735) & 440.36 (10.292) & 463.777 (11.56) & 443.523 (8.565) & 443.526 (8.613) & 507.775 (13.893) & 419.822 (10.689)\\
concrete & 46.925 (3.091) & 47.929 (3.895) & 47.62 (3.517) & 49.55 (3.507) & 49.51 (3.492) & 53.478 (3.195) & 49.516 (3.629)\\
cycle & 32.565 (0.658) & 33.112 (0.645) & 33.87 (0.62) & 39.133 (0.622) & 39.347 (0.639) & 43.835 (0.949) & 35.287 (0.711)\\
electric & 0.084 (0.002) & 0.101 (0.001) & 0.099 (0.002) & 0.105 (0.002) & 0.105 (0.002) & 0.115 (0.002) & 0.1 (0.002)\\
homes & 940824.14 (54169.436) & 1063287.542 (83041.223) & 1102103.112 (84129.477) & 1149649.524 (92088.974) & 1169346.82 (94930.369) & 1762462.154 (167630.458) & 1316917.411 (125290.599)\\
meps19 & 73.538 (9.282) & 73.914 (8.904) & 74.708 (9.329) & 73.988 (9.315) & 73.987 (9.315) & 84.099 (10.59) & 72.798 (8.977)\\
protein & 17.562 (0.101) & 17.8 (0.104) & 18.156 (0.109) & 17.804 (0.09) & 17.804 (0.09) & 18.276 (0.085) & 17.795 (0.091)\\
star & 1039.011 (38.939) & 1058.143 (43.397) & 1044.706 (40.742) & 1043.497 (41.667) & 1043.94 (41.71) & 1069.002 (38.253) & 1064.049 (41.105)\\
superconductivity & 74.955 (1.132) & 78.307 (1.142) & 82.005 (1.185) & 78.262 (1.097) & 78.263 (1.098) & 85.342 (1.062) & 76.787 (1.226)\\
WEC & 258650.41 (5075.131) & 307021.812 (5053.901) & 283550.702 (5296.65) & 319576.121 (4757.143) & 320076.174 (4777.112) & 347431.5 (5157.103) & 310371.018 (4875.144)\\
winered & 3.312 (0.288) & 3.361 (0.332) & 3.332 (0.328) & 3.369 (0.379) & 3.367 (0.379) & 3.258 (0.351) & 3.333 (0.343)\\
winewhite & 3.969 (0.252) & 4.184 (0.269) & 4.24 (0.275) & 4.308 (0.292) & 4.306 (0.292) & 4.308 (0.253) & 4.079 (0.27)\\
\bottomrule\end{tabular}

* coverage per outlier:

In [10]:
output_cover = pd.read_pickle(folder_path + "/result_cover_outlier.pkl")
output_cover

,Dataset,ECP-MDN,ECP-BART,ECP-GP,CQR,CQR-r,UACQR-P,UACQR-S
0,airfoil,0.902 (0.024),0.894 (0.029),0.875 (0.032),0.877 (0.031),0.876 (0.032),0.875 (0.033),0.872 (0.031)
1,bike,0.894 (0.011),0.885 (0.009),0.9 (0.011),0.882 (0.01),0.882 (0.01),0.887 (0.009),0.885 (0.009)
2,concrete,0.875 (0.038),0.824 (0.039),0.855 (0.034),0.845 (0.035),0.844 (0.036),0.878 (0.032),0.845 (0.034)
3,cycle,0.906 (0.011),0.907 (0.009),0.908 (0.01),0.9 (0.009),0.901 (0.009),0.909 (0.01),0.906 (0.009)
4,electric,0.895 (0.009),0.887 (0.01),0.887 (0.009),0.888 (0.009),0.888 (0.009),0.889 (0.01),0.889 (0.009)
5,homes,0.895 (0.008),0.89 (0.007),0.885 (0.007),0.883 (0.007),0.88 (0.007),0.864 (0.009),0.872 (0.007)
6,meps19,0.899 (0.009),0.904 (0.008),0.903 (0.008),0.897 (0.008),0.897 (0.008),0.9 (0.008),0.897 (0.008)
7,protein,0.896 (0.005),0.893 (0.005),0.895 (0.005),0.894 (0.004),0.894 (0.004),0.894 (0.005),0.894 (0.004)
8,star,0.876 (0.016),0.867 (0.016),0.871 (0.017),0.875 (0.018),0.875 (0.018),0.911 (0.021),0.87 (0.018)
9,superconductivity,0.879 (0.008),0.863 (0.008),0.872 (0.009),0.913 (0.006),0.912 (0.006),0.932 (0.005),0.912 (0.006)
10,WEC,0.86 (0.009),0.901 (0.006),0.864 (0.008),0.927 (0.005),0.926 (0.005),0.917 (0.005),0.921 (0.005)
11,winered,0.892 (0.026),0.875 (0.029),0.876 (0.03),0.846 (0.032),0.847 (0.032),0.861 (0.033),0.848 (0.032)
12,winewhite,0.868 (0.014),0.86 (0.015),0.854 (0.016),0.847 (0.016),0.847 (0.016),0.865 (0.02),0.861 (0.016)

In [11]:
custom_table_generator(output_cover)

\begin{tabular}{lccccccc}\toprule
Dataset & ECP-MDN & ECP-BART & ECP-GP & CQR & CQR-r & UACQR-P & UACQR-S\\\midrule
airfoil & 0.902 (0.024) & 0.894 (0.029) & 0.875 (0.032) & 0.877 (0.031) & 0.876 (0.032) & 0.875 (0.033) & 0.872 (0.031)\\
bike & 0.894 (0.011) & 0.885 (0.009) & 0.9 (0.011) & 0.882 (0.01) & 0.882 (0.01) & 0.887 (0.009) & 0.885 (0.009)\\
concrete & 0.875 (0.038) & 0.824 (0.039) & 0.855 (0.034) & 0.845 (0.035) & 0.844 (0.036) & 0.878 (0.032) & 0.845 (0.034)\\
cycle & 0.906 (0.011) & 0.907 (0.009) & 0.908 (0.01) & 0.9 (0.009) & 0.901 (0.009) & 0.909 (0.01) & 0.906 (0.009)\\
electric & 0.895 (0.009) & 0.887 (0.01) & 0.887 (0.009) & 0.888 (0.009) & 0.888 (0.009) & 0.889 (0.01) & 0.889 (0.009)\\
homes & 0.895 (0.008) & 0.89 (0.007) & 0.885 (0.007) & 0.883 (0.007) & 0.88 (0.007) & 0.864 (0.009) & 0.872 (0.007)\\
meps19 & 0.899 (0.009) & 0.904 (0.008) & 0.903 (0.008) & 0.897 (0.008) & 0.897 (0.008) & 0.9 (0.008) & 0.897 (0.008)\\
protein & 0.896 (0.005) & 0.893 (0.005) & 0.895 (0.005) & 0.894 (0.004) & 0.894 (0.004) & 0.894 (0.005) & 0.894 (0.004)\\
star & 0.876 (0.016) & 0.867 (0.016) & 0.871 (0.017) & 0.875 (0.018) & 0.875 (0.018) & 0.911 (0.021) & 0.87 (0.018)\\
superconductivity & 0.879 (0.008) & 0.863 (0.008) & 0.872 (0.009) & 0.913 (0.006) & 0.912 (0.006) & 0.932 (0.005) & 0.912 (0.006)\\
WEC & 0.86 (0.009) & 0.901 (0.006) & 0.864 (0.008) & 0.927 (0.005) & 0.926 (0.005) & 0.917 (0.005) & 0.921 (0.005)\\
winered & 0.892 (0.026) & 0.875 (0.029) & 0.876 (0.03) & 0.846 (0.032) & 0.847 (0.032) & 0.861 (0.033) & 0.848 (0.032)\\
winewhite & 0.868 (0.014) & 0.86 (0.015) & 0.854 (0.016) & 0.847 (0.016) & 0.847 (0.016) & 0.865 (0.02) & 0.861 (0.016)\\
\bottomrule\end{tabular}

## Regression results:

Reading pickle files and transforming to table:
* Interval length ratio between outlier and inliers:

In [12]:
output_ratio = pd.read_pickle(folder_path + 
                              "/reg_result_ratio_outlier.pkl")
output_ratio

,Dataset,ECP-MDN,ECP-BART,ECP-GP,Mondrian,Reg-split,Weighted
0,airfoil,1.03 (0.035),1.021 (0.039),1.004 (0.014),0.988 (0.023),1.0 (0.0),1.03 (0.045)
1,bike,0.963 (0.02),0.971 (0.014),0.98 (0.006),1.029 (0.018),1.0 (0.0),0.976 (0.016)
2,concrete,1.11 (0.035),1.05 (0.036),1.03 (0.018),0.99 (0.036),1.0 (0.0),1.137 (0.067)
3,cycle,0.973 (0.008),0.967 (0.007),0.992 (0.002),1.005 (0.006),1.0 (0.0),0.988 (0.005)
4,electric,0.992 (0.01),0.987 (0.008),1.0 (0.003),0.996 (0.005),1.0 (0.0),0.992 (0.008)
5,homes,1.268 (0.035),1.124 (0.019),1.138 (0.015),1.234 (0.026),1.0 (0.0),1.203 (0.035)
6,meps19,1.097 (0.065),1.047 (0.027),1.057 (0.041),1.099 (0.05),1.0 (0.0),1.074 (0.058)
7,protein,1.008 (0.004),0.999 (0.002),0.996 (0.003),1.003 (0.004),1.0 (0.0),1.0 (0.005)
8,star,1.005 (0.007),1.0 (0.007),1.0 (0.0),1.016 (0.011),1.0 (0.0),0.984 (0.025)
9,superconductivity,1.107 (0.016),1.129 (0.014),1.061 (0.009),1.211 (0.014),1.0 (0.0),1.111 (0.017)
10,WEC,1.122 (0.015),1.077 (0.007),1.034 (0.005),1.2 (0.014),1.0 (0.0),1.041 (0.007)
11,winered,1.143 (0.027),1.055 (0.019),1.031 (0.009),1.052 (0.02),1.0 (0.0),1.095 (0.045)
12,winewhite,1.039 (0.012),1.01 (0.007),1.001 (0.001),1.058 (0.013),1.0 (0.0),0.997 (0.011)

In [13]:
custom_table_generator(output_ratio)

\begin{tabular}{lcccccc}\toprule
Dataset & ECP-MDN & ECP-BART & ECP-GP & Mondrian & Reg-split & Weighted\\\midrule
airfoil & 1.03 (0.035) & 1.021 (0.039) & 1.004 (0.014) & 0.988 (0.023) & 1.0 (0.0) & 1.03 (0.045)\\
bike & 0.963 (0.02) & 0.971 (0.014) & 0.98 (0.006) & 1.029 (0.018) & 1.0 (0.0) & 0.976 (0.016)\\
concrete & 1.11 (0.035) & 1.05 (0.036) & 1.03 (0.018) & 0.99 (0.036) & 1.0 (0.0) & 1.137 (0.067)\\
cycle & 0.973 (0.008) & 0.967 (0.007) & 0.992 (0.002) & 1.005 (0.006) & 1.0 (0.0) & 0.988 (0.005)\\
electric & 0.992 (0.01) & 0.987 (0.008) & 1.0 (0.003) & 0.996 (0.005) & 1.0 (0.0) & 0.992 (0.008)\\
homes & 1.268 (0.035) & 1.124 (0.019) & 1.138 (0.015) & 1.234 (0.026) & 1.0 (0.0) & 1.203 (0.035)\\
meps19 & 1.097 (0.065) & 1.047 (0.027) & 1.057 (0.041) & 1.099 (0.05) & 1.0 (0.0) & 1.074 (0.058)\\
protein & 1.008 (0.004) & 0.999 (0.002) & 0.996 (0.003) & 1.003 (0.004) & 1.0 (0.0) & 1.0 (0.005)\\
star & 1.005 (0.007) & 1.0 (0.007) & 1.0 (0.0) & 1.016 (0.011) & 1.0 (0.0) & 0.984 (0.025)\\
superconductivity & 1.107 (0.016) & 1.129 (0.014) & 1.061 (0.009) & 1.211 (0.014) & 1.0 (0.0) & 1.111 (0.017)\\
WEC & 1.122 (0.015) & 1.077 (0.007) & 1.034 (0.005) & 1.2 (0.014) & 1.0 (0.0) & 1.041 (0.007)\\
winered & 1.143 (0.027) & 1.055 (0.019) & 1.031 (0.009) & 1.052 (0.02) & 1.0 (0.0) & 1.095 (0.045)\\
winewhite & 1.039 (0.012) & 1.01 (0.007) & 1.001 (0.001) & 1.058 (0.013) & 1.0 (0.0) & 0.997 (0.011)\\
\bottomrule\end{tabular}

* AISL per outlier:

In [14]:
output_aisl = pd.read_pickle(folder_path + "/reg_result_aisl_outlier.pkl")
output_aisl

,Dataset,ECP-MDN,ECP-BART,ECP-GP,Mondrian,Reg-split,Weighted
0,airfoil,22.559 (3.77),20.628 (1.711),21.614 (3.048),22.93 (2.334),21.072 (2.025),21.504 (1.993)
1,bike,368.759 (16.328),356.572 (16.402),415.154 (19.885),375.29 (16.131),435.934 (18.582),372.581 (15.851)
2,concrete,57.452 (5.099),60.544 (7.612),56.568 (5.818),65.992 (7.706),58.84 (7.077),70.954 (9.869)
3,cycle,19.793 (0.725),19.919 (0.827),19.73 (0.743),19.723 (0.724),19.987 (0.811),19.703 (0.709)
4,electric,0.047 (0.002),0.047 (0.001),0.049 (0.002),0.049 (0.001),0.049 (0.002),0.047 (0.001)
5,homes,699684.475 (31521.259),829601.512 (53644.809),839898.008 (54645.453),770438.874 (48753.286),1116939.518 (80329.669),775915.273 (43140.629)
6,meps19,82.079 (8.701),105.458 (13.515),101.512 (10.195),91.053 (12.467),129.506 (15.297),111.854 (15.951)
7,protein,18.4 (0.273),19.752 (0.312),19.66 (0.305),18.19 (0.281),20.258 (0.299),19.05 (0.331)
8,star,1086.411 (54.835),1101.786 (50.98),1095.85 (61.626),1110.629 (46.268),1098.965 (57.668),1336.506 (71.481)
9,superconductivity,63.083 (2.454),64.565 (2.311),67.785 (2.489),64.191 (1.752),73.123 (2.068),64.048 (2.127)
10,WEC,171374.676 (5005.243),200857.096 (6939.505),199590.043 (6719.942),166764.841 (5790.554),215398.077 (7283.632),200393.215 (6243.335)
11,winered,3.651 (0.287),3.778 (0.448),4.216 (0.374),3.979 (0.29),4.051 (0.43),4.323 (0.414)
12,winewhite,3.642 (0.227),3.754 (0.263),3.769 (0.257),3.584 (0.209),3.758 (0.254),3.854 (0.244)

In [15]:
custom_table_generator(output_aisl)

\begin{tabular}{lcccccc}\toprule
Dataset & ECP-MDN & ECP-BART & ECP-GP & Mondrian & Reg-split & Weighted\\\midrule
airfoil & 22.559 (3.77) & 20.628 (1.711) & 21.614 (3.048) & 22.93 (2.334) & 21.072 (2.025) & 21.504 (1.993)\\
bike & 368.759 (16.328) & 356.572 (16.402) & 415.154 (19.885) & 375.29 (16.131) & 435.934 (18.582) & 372.581 (15.851)\\
concrete & 57.452 (5.099) & 60.544 (7.612) & 56.568 (5.818) & 65.992 (7.706) & 58.84 (7.077) & 70.954 (9.869)\\
cycle & 19.793 (0.725) & 19.919 (0.827) & 19.73 (0.743) & 19.723 (0.724) & 19.987 (0.811) & 19.703 (0.709)\\
electric & 0.047 (0.002) & 0.047 (0.001) & 0.049 (0.002) & 0.049 (0.001) & 0.049 (0.002) & 0.047 (0.001)\\
homes & 699684.475 (31521.259) & 829601.512 (53644.809) & 839898.008 (54645.453) & 770438.874 (48753.286) & 1116939.518 (80329.669) & 775915.273 (43140.629)\\
meps19 & 82.079 (8.701) & 105.458 (13.515) & 101.512 (10.195) & 91.053 (12.467) & 129.506 (15.297) & 111.854 (15.951)\\
protein & 18.4 (0.273) & 19.752 (0.312) & 19.66 (0.305) & 18.19 (0.281) & 20.258 (0.299) & 19.05 (0.331)\\
star & 1086.411 (54.835) & 1101.786 (50.98) & 1095.85 (61.626) & 1110.629 (46.268) & 1098.965 (57.668) & 1336.506 (71.481)\\
superconductivity & 63.083 (2.454) & 64.565 (2.311) & 67.785 (2.489) & 64.191 (1.752) & 73.123 (2.068) & 64.048 (2.127)\\
WEC & 171374.676 (5005.243) & 200857.096 (6939.505) & 199590.043 (6719.942) & 166764.841 (5790.554) & 215398.077 (7283.632) & 200393.215 (6243.335)\\
winered & 3.651 (0.287) & 3.778 (0.448) & 4.216 (0.374) & 3.979 (0.29) & 4.051 (0.43) & 4.323 (0.414)\\
winewhite & 3.642 (0.227) & 3.754 (0.263) & 3.769 (0.257) & 3.584 (0.209) & 3.758 (0.254) & 3.854 (0.244)\\
\bottomrule\end{tabular}

* Coverage per outlier:

In [16]:
output_cover = pd.read_pickle(folder_path + "/reg_result_cover_outlier.pkl")
output_cover

,Dataset,ECP-MDN,ECP-BART,ECP-GP,Mondrian,Reg-split,Weighted
0,airfoil,0.894 (0.027),0.896 (0.027),0.883 (0.028),0.91 (0.025),0.902 (0.023),0.903 (0.021)
1,bike,0.897 (0.01),0.895 (0.01),0.901 (0.011),0.909 (0.009),0.903 (0.01),0.895 (0.009)
2,concrete,0.893 (0.028),0.895 (0.029),0.902 (0.027),0.904 (0.023),0.873 (0.033),0.876 (0.029)
3,cycle,0.892 (0.008),0.89 (0.009),0.901 (0.01),0.914 (0.008),0.901 (0.009),0.898 (0.009)
4,electric,0.902 (0.008),0.9 (0.008),0.898 (0.01),0.909 (0.008),0.906 (0.009),0.911 (0.009)
5,homes,0.896 (0.006),0.869 (0.008),0.873 (0.008),0.894 (0.007),0.847 (0.008),0.878 (0.008)
6,meps19,0.899 (0.008),0.899 (0.007),0.9 (0.007),0.901 (0.012),0.894 (0.008),0.898 (0.007)
7,protein,0.89 (0.005),0.89 (0.005),0.892 (0.005),0.898 (0.004),0.895 (0.004),0.892 (0.004)
8,star,0.906 (0.018),0.892 (0.019),0.899 (0.019),0.899 (0.015),0.885 (0.02),0.879 (0.018)
9,superconductivity,0.887 (0.008),0.891 (0.007),0.872 (0.008),0.918 (0.005),0.884 (0.007),0.888 (0.006)
10,WEC,0.871 (0.006),0.861 (0.006),0.85 (0.007),0.897 (0.005),0.85 (0.006),0.852 (0.006)
11,winered,0.881 (0.027),0.87 (0.028),0.841 (0.029),0.858 (0.024),0.843 (0.031),0.846 (0.029)
12,winewhite,0.878 (0.016),0.872 (0.015),0.876 (0.014),0.9 (0.011),0.863 (0.015),0.867 (0.016)

In [17]:
custom_table_generator(output_cover)

\begin{tabular}{lcccccc}\toprule
Dataset & ECP-MDN & ECP-BART & ECP-GP & Mondrian & Reg-split & Weighted\\\midrule
airfoil & 0.894 (0.027) & 0.896 (0.027) & 0.883 (0.028) & 0.91 (0.025) & 0.902 (0.023) & 0.903 (0.021)\\
bike & 0.897 (0.01) & 0.895 (0.01) & 0.901 (0.011) & 0.909 (0.009) & 0.903 (0.01) & 0.895 (0.009)\\
concrete & 0.893 (0.028) & 0.895 (0.029) & 0.902 (0.027) & 0.904 (0.023) & 0.873 (0.033) & 0.876 (0.029)\\
cycle & 0.892 (0.008) & 0.89 (0.009) & 0.901 (0.01) & 0.914 (0.008) & 0.901 (0.009) & 0.898 (0.009)\\
electric & 0.902 (0.008) & 0.9 (0.008) & 0.898 (0.01) & 0.909 (0.008) & 0.906 (0.009) & 0.911 (0.009)\\
homes & 0.896 (0.006) & 0.869 (0.008) & 0.873 (0.008) & 0.894 (0.007) & 0.847 (0.008) & 0.878 (0.008)\\
meps19 & 0.899 (0.008) & 0.899 (0.007) & 0.9 (0.007) & 0.901 (0.012) & 0.894 (0.008) & 0.898 (0.007)\\
protein & 0.89 (0.005) & 0.89 (0.005) & 0.892 (0.005) & 0.898 (0.004) & 0.895 (0.004) & 0.892 (0.004)\\
star & 0.906 (0.018) & 0.892 (0.019) & 0.899 (0.019) & 0.899 (0.015) & 0.885 (0.02) & 0.879 (0.018)\\
superconductivity & 0.887 (0.008) & 0.891 (0.007) & 0.872 (0.008) & 0.918 (0.005) & 0.884 (0.007) & 0.888 (0.006)\\
WEC & 0.871 (0.006) & 0.861 (0.006) & 0.85 (0.007) & 0.897 (0.005) & 0.85 (0.006) & 0.852 (0.006)\\
winered & 0.881 (0.027) & 0.87 (0.028) & 0.841 (0.029) & 0.858 (0.024) & 0.843 (0.031) & 0.846 (0.029)\\
winewhite & 0.878 (0.016) & 0.872 (0.015) & 0.876 (0.014) & 0.9 (0.011) & 0.863 (0.015) & 0.867 (0.016)\\
\bottomrule\end{tabular}